### ISSUE TITLE
Не хватает заголовка таблицы

### ISSUE THREAD

**Issue by lukasvs** [yandex-money/yandex-money-cms-v2-drupal#11]
https://github.com/yandex-money/yandex-money-cms-v2-drupal/blob/aa2d3805586eadc55359830a604020496a4c7f78/transactions.inc#L231

Не хватает заголовка таблицы для payment_id. Таблица выводится из-за этого невалидно

**Comment by ostulov** [comment]
Уточните, как образом Вы используете данный функционал? 
На текущий момент он не задействован и мы планируем его удалить.

**Comment by lukasvs** [comment]
Как использую? Просто просматриваю страницу

**Comment by ostulov** [comment]
Исправлено в релизе v1.0.11
