### ISSUE TITLE
Не работают транзакции

### ISSUE THREAD

**Issue by lukasvs** [yandex-money/yandex-money-cms-v2-drupal#13]
После успешной оплаты транзакция заказа висит в статусе ожидания. Баланс заказа не изменяется

**Comment by ostulov** [comment]
Для решения проблемы Вам необходимо в первую очередь сверить адрес для уведомления об успешной оплате. Адрес из настроек модуля должен быть указан в личном кабинете Яндекс.Кассы.
Если адрес совпадает, но проблема продолжает возникать, Вам необходимо написать в техподдержку по почте poisk@yamoney.ru или cms@yamoney.ru, уточнив свой shopid.

**Comment by lukasvs** [comment]
http://powm.loc/yamoney_api/commerce/notify
Only required if Yandex.Checkout's specialists ask for it
Адрес не менялся самостоятельно...
сюда cms@yamoney.ru уже писал, сказали, что передадут разработчикам, но пока ничего...

**Comment by lukasvs** [comment]
К сожалению, мы были вынуждены откатиться на старую версию и сверить сейчас не получится, но уверяю вас, что все было по дефолту

**Comment by ostulov** [comment]
Если Вы уверены, что адрес совпадает, но проблема продолжает возникать, Вам необходимо написать в техподдержку по почте poisk@yamoney.ru или cms@yamoney.ru, уточнив свой shopid.
Техподдержка Яндекс.Кассы по shopid может посмотреть, в чем причина недоставленного уведомления.
