### ISSUE TITLE
Поддержка Drupal 8

### ISSUE THREAD

**Issue by titovm** [yandex-money/yandex-money-cms-v2-drupal#17]
Планируется ли разработка модуля Яндекс денег для Drupal 8 Commerce 2?

**Comment by ostulov** [comment]
Добрый день!

Разработка модуля под Drupal 8 Commerce 2 планируется. Пока точный срок выхода назвать не могу.

**Comment by ostulov** [comment]
https://github.com/yandex-money/yandex-money-cms-v2-drupal8
