### ISSUE TITLE
Ошибка при переходе на закладку Оплата в админке

### ISSUE THREAD

**Issue by ntym4ek** [yandex-money/yandex-money-cms-v2-drupal#23]
По ссылке /admin/commerce/orders/%order_id/payment возникает ошибка
"Recoverable fatal error: Object of class stdClass could not be converted to string в функции DatabaseStatementBase->execute() (строка 2227 в файле /var/www/user/data/www/dev.site.ru/includes/database/database.inc)."

Связано это с некорректным названием внутренней функции загрузки транзакции ya_commerce_api_commerce_payment_transaction_load. Оно совпадает с названием хука hook_commerce_payment_transaction_load модуля commerce_payment. Поэтому при вызове ya_commerce_api_commerce_payment_transaction_load срабатывает хук hook_commerce_payment_transaction_load. Получаем бесконечный цикл, обрывающийся из-за несовпадения входных параметров.

Лечится изменением названия функции ya_commerce_api_commerce_payment_transaction_load.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за подробное описание, исправим.

**Comment by lukasvs** [comment]
Пол года ждём...

**Comment by ntym4ek** [comment]
Этот баг они поправили, но из-за остальных ошибок модуль можно использовать только в магазине с ограниченной функциональностью.
