### ISSUE TITLE
Критическая ошибка с Commerce Discount и ФЗ54

### ISSUE THREAD

**Issue by ntym4ek** [yandex-money/yandex-money-cms-v2-drupal#33]
При установленной в настройках модуля опции "Отправлять в Яндекс.Кассу данные для чеков (54-ФЗ)" и наличии в магазине скидок на товар в чек отправляются цены без скидки, что приводит к отмене оплаты на стороне Яндекс.Кассы.

**Comment by ostulov** [comment]
Исправлено в версии v1.0.19
