### ISSUE TITLE
Критическая ошибка с Commerce Coupon и ФЗ54

### ISSUE THREAD

**Issue by ntym4ek** [yandex-money/yandex-money-cms-v2-drupal#35]
Включена опция "Отправлять в Яндекс.Кассу данные для чеков (54-ФЗ)". 
В магазине есть купоны, применяемые к сумме заказа, а не отдельным товарам.

При попытке оплатить заказ с таким купоном Яндекс отменит платёж из-за отличия сумм в чеке для онлайн кассы и суммой, передаваемой к оплате.

Такой тип купона регистрирует компонент цены не для каждого товара в commerce_line_item, а для общей суммы заказа в commerce_order_total.
При составлении чека для отправки в онлайн кассу ваш модуль берет цены из commerce_line_items и их сумма оказывается больше, чем общая сумма заказа в commerce_order_total, где присутствует компонент купона.

Ваш модуль не учитывает возможное наличие компонент суммы в commerce_order_total.

**Comment by ostulov** [comment]
Благодарю за сообщение. Рассмотрим возможность совместимости с Commerce Coupon

**Comment by ostulov** [comment]
Исправлено в версии v1.0.19
