### ISSUE TITLE
Notice: Undefined index: payment_method

### ISSUE THREAD

**Issue by lukasvs** [yandex-money/yandex-money-cms-v2-drupal#7]
После завершения оплаты в журнале:

Notice: Undefined index: payment_method в функции ya_commerce_api_submit_form_validate() (строка 227 в файле .../yamoney_api/ya_commerce/ya_commerce_api.module).

Notice: Undefined index: payment_method в функции ya_commerce_api_submit_form_validate() (строка 235 в файле .../yamoney_api/ya_commerce/ya_commerce_api.module).

**Comment by ostulov** [comment]
Добрый день!

Для разбора данной проблемы напишите письмо на почту cms@yamoney с приложением подробной информации о возникающей проблеме, доступами в админпанель сайта и к ftp.

**Comment by lukasvs** [comment]
Вы смеётесь? У меня на сервере нет ftp. И давать доступ??? У вас не возникает данной продлемы? Создайте страницу проекта на орге!

**Comment by mirazhg** [comment]
Подтверждаю наличие этой проблемы. Надеюсь в следующих релизах это исправят.

**Comment by ostulov** [comment]
Исправлено в v1.0.13
